### ISSUE TITLE
Generate platform channel code from style specification

### ISSUE THREAD

**Issue by tobrun** [mapbox/flutter-mapbox-gl#11]
Flutter uses the concept of [platform channels](https://flutter.io/platform-channels/) to allow to execute platform specific code. To streamline integration between iOS and Android, we can use the [style specifcation](https://www.mapbox.com/mapbox-gl-js/style-spec/) to generate the code.

**Comment by 1ec5** [comment]
React Native Mapbox GL jumps through [some hoops](https://github.com/mapbox/react-native-mapbox-gl/blob/master/scripts/templates/styleMap.js.ejs) to reverse-engineer the iOS map SDK’s translation from style specification naming conventions to Cocoa naming conventions. Perhaps some of that code could be reused.
