### ISSUE TITLE
iOS integration

### ISSUE THREAD

**Issue by tobrun** [mapbox/flutter-mapbox-gl#12]
Atm this repository only supports running flutter-mapbox-gl on Android, to be able to publish this a flutter package we need to support both platforms.

**Comment by 1ec5** [comment]
At least for the moment, Flutter’s iOS implementation includes an undocumented [FlutterTextureRegistry](https://docs.flutter.io/objcdoc/Protocols/FlutterTextureRegistry.html) that could be used to implement an OpenGL ES–based widget. (It reminds me of the iOS map SDK’s MGLOpenGLStyleLayer.) However, the API is based on Core Video, which is distinct from the GLKit framework we use in the iOS map SDK. Specifically, you copy over a [CVPixelBuffer](https://developer.apple.com/documentation/corevideo/cvpixelbuffer-q2e) on every frame.

The iOS map SDK might need some major changes to elegantly support this architecture. On the other hand, it might be worth exploring whether a Core Animation layer could be the basis of a workaround.

**Comment by 1ec5** [comment]
> to be able to publish this a flutter package we need to support both platforms

Fortunately, this doesn’t appear to be the case, so this issue won’t block an initial release.

**Comment by bramvbilsen** [comment]
Is there an ETA for this?

**Comment by Fontinalis** [comment]
Any update on this?

**Comment by csjames** [comment]
^ :)

**Comment by tobrun** [comment]
I'm unable to give an ETA as this isn't an official Mapbox product (yet) and it's hard to make a case internally due to the lack of attention Google gave to Flutter at last Google I/O. That said, we are looking for contributions and would love if the community could chime in and help us out!

**Comment by Fontinalis** [comment]
Like I commented in an other issue, got the Mapbox working on iOS and started working on it, happy to create a pull request as soon as it gets there!
