### ISSUE TITLE
Expose CameraUpdateFactory API

### ISSUE THREAD

**Issue by tobrun** [mapbox/flutter-mapbox-gl#13]
On the Android SDK we expose the [CameraUpdateFactory API](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraUpdateFactory.java) to allow end developers to animate/change the camera position of the map.  At minimum we should expose an `animateTo/flyTo` equivalent as API for end developers.

**Comment by tobrun** [comment]
flyTo is being worked on in https://github.com/mapbox/flutter-mapbox-gl/pull/18.
What is missing to close this issue:
 - [ ] jumpTo
 - [ ] easeTo

**Comment by seddonm1** [comment]
you can close this.
