### ISSUE TITLE
Add map snapshotter API

### ISSUE THREAD

**Issue by tobrun** [mapbox/flutter-mapbox-gl#24]
The iOS & Android SDKs allow to generate static images from a map in two ways:
 - capturing an image from the currently shown map (eg. [iOS](https://www.mapbox.com/ios-sdk/examples/map-snapshotter/))
 - render an image from a deifintion using the MapSnapshotter (eg. [Android](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/snapshot/MapSnapshotterActivity.java#L95))

**Comment by 1ec5** [comment]
> capturing an image from the currently shown map (eg. [iOS](https://www.mapbox.com/ios-sdk/examples/map-snapshotter/))

To clarify, this example just _happens_ to snapshot what’s shown on the map, but the gist of that example is that you can snapshot any region of the map.
