### ISSUE TITLE
Add marker api

### ISSUE THREAD

**Issue by seddonm1** [mapbox/flutter-mapbox-gl#28]
@tobrun I have tried to add the addMarker capability (without custom icon to start) but seeing an Java exception:

```
E/MethodChannel#com.mapbox/flutter_mapbox(14564): Failed to handle method call
E/MethodChannel#com.mapbox/flutter_mapbox(14564): java.lang.NullPointerException
E/MethodChannel#com.mapbox/flutter_mapbox(14564): 	at com.mapbox.mapboxsdk.maps.NativeMapView.nativeAddMarkers(Native Method)
E/MethodChannel#com.mapbox/flutter_mapbox(14564): 	at com.mapbox.mapboxsdk.maps.NativeMapView.addMarker(NativeMapView.java:406)
```

This looks like an upstream problem as the Marker object is correct. can you have a look? https://github.com/seddonm1/flutter-mapbox-gl/tree/add-marker

**Comment by tobrun** [comment]
Could be related to the icon image? Haven't had time to look into this, just wanted to flag that we are going to rework the annotations API upstream, so might be better holding of development of this feature until that lands. If you feel this can't wait, feel free to move forward.

**Comment by tobrun** [comment]
upstream seems to not be happening in the near future, so maybe we should move forward with the annotations approach

**Comment by MrRik2** [comment]
Hm.. You can use this code in `FlutterMap.java`:
```java
public void addMarker(Marker marker) {
    MarkerOptions options = new MarkerOptions()
        .icon(IconFactory.getInstance(context).defaultMarker())
        .position(marker.getPosition())
        .snippet(marker.getSnippet())
        .title(marker.getTitle());
    nativeMapView.addMarker(new Marker(options));
```
Now, i not founded any exception, but marker does not appear.
Maybe `IconFactory.getInstance(context).defaultMarker()` - returned empty icon?

**Comment by kaiquegazola** [comment]
@tobrun any updates?

**Comment by tobrun** [comment]
@kaiquegazola we are working on improving annotations api in https://github.com/mapbox/mapbox-plugins-android/tree/master/plugin-annotation. Once finalised, we will work on integrating this inside this project.

**Comment by Ivaskuu** [comment]
@tobrun Any updates on this? This is the perfect plugin for me, except that it lacks the ability to add markers. It would be cool if we could also specify a custom Flutter widget for the marker icon!

**Comment by tobrun** [comment]
This project will be moved to https://github.com/tobrun/flutter-mapbox-gl
Marker API through the annotation plugin is one of the most important features to support.
This feature request was added to tobrun/flutter-mapbox-gl#4 (comment)
