### ISSUE TITLE
Fix density/pixelratio

### ISSUE THREAD

**Issue by tobrun** [mapbox/flutter-mapbox-gl#3]
When running the project, it's noticable that labels are oversized:

![ezgif com-video-to-gif 62](https://user-images.githubusercontent.com/2151639/39235392-107b0efe-4876-11e8-971a-706fd486e53e.gif)

**Comment by seddonm1** [comment]
Was this comment before or after your https://github.com/mapbox/mapbox-gl-native/pull/11772 change?

Currently code will not compile as it is dependent on that change being implemented upstream. 

FYI for anyone testing until that upstream change gets released just change:
```
    nativeMapView = new NativeMapView(context, 1, this, mapRenderer);
to:
    nativeMapView = new NativeMapView(context, this, mapRenderer);
```

**Comment by seddonm1** [comment]
#17 

do you think https://github.com/mapbox/mapbox-gl-native/pull/11772 can be included into 6.1.0-snapshot?

**Comment by A139834** [comment]
Thanks. ill quickly fix the https://github.com/mapbox/flutter-mapbox-gl/pull/17

**Comment by seddonm1** [comment]
No worries. Ill quickly fix my PR

**Comment by tobrun** [comment]
Finally got to the bottom of this: Flutter exposes 2 coordinate systems called local and global. You can convert between the two using box.globalToLocal and box.localToGlobal. These coordinate systems do not match what we expect on the map side (same input as on android), to support this we need to convert local to the expected pixel output using the device pixel ratio. This is needed when the map is created and when we receive inputs from the flutter framework (eg. gesture input). Due to limited flutter knowledge I'm going to punt on this for now, map renders at correct resolution and gestures work as expected.
