### ISSUE TITLE
Markers not showing up.

### ISSUE THREAD

**Issue by tomialagbe** [mapbox/flutter-mapbox-gl#47]
I have tried to add markers using the default marker icon.
I don't get any errors, but the markers do not show up. Below is my code.

`
FlutterMap flutterMap = maps.get(textureId).map;
IconFactory iconFactory = IconFactory.getInstance(activity);
Icon markerIcon = iconFactory.iconFactory.defaultMarker();
Marker marker = new MarkerOptions()
  .position(new LatLng(lat, lng))
  .title(title)
  .snippet(snippet)
  .icon(markerIcon)
  .getMarker();
  long markerId = flutterMap.addMarker(marker);
`

**Comment by quangIO** [comment]
```  
public void addMarker() {
    IconFactory iconFactory = IconFactory.getInstance(context);
    Icon markerIcon = iconFactory.defaultMarker();
    nativeMapView.addMarker(new Marker(new MarkerOptions().position(new LatLng(51.530643, -0.122998)).icon(markerIcon).title("Bug")));
  }
``` 
I tried a minimal one but it still does not work. My current workaround is using Stack widget + getOffsetForLatLng.

**Comment by tomialagbe** [comment]
@quangIO How do you update the position of the marker when the user drags the screen, or the user changes location

**Comment by Asoseil** [comment]
how can i add a marker? seems that there is no addMarker method in the lib

**Comment by tobrun** [comment]
I'm also a bit confused, that API isn't available yet. 
If you are interested in contributing, feel free to add it and open a PR!
