### ISSUE TITLE
Add tilt/shove gesture

### ISSUE THREAD

**Issue by tobrun** [mapbox/flutter-mapbox-gl#5]
Scrolling vertically with two fingers should increase/decrease the tilt of the camera position.

**Comment by tobrun** [comment]
This kind of gesture isn't currently supported by flutter, full list [here](https://docs.flutter.io/flutter/widgets/GestureDetector/GestureDetector.html).

**Comment by ansarikhurshid786** [comment]
yes also dragging map is not smooth in android

**Comment by tobrun** [comment]
with moving to a platform view this issue is no longer applicable, we can leverage touch handling from the native sdks instead.
