### ISSUE TITLE
Error when using in a new project

### ISSUE THREAD

**Issue by RNMBuser** [mapbox/flutter-mapbox-gl#51]
After adding the Mapbox imports on MainActivity.java that are missing in the Getting Started guide 

```
import com.mapbox.mapboxsdk.*;
import com.mapbox.mapboxsdk.maps.*;
import com.mapbox.mapboxsdk.maps.*;
import com.mapbox.mapboxsdk.camera.*;
import com.mapbox.mapboxsdk.geometry.*;
import com.mapbox.mapboxsdk.constants.*;
import com.mapbox.mapboxsdk.annotations.*;
```

I still get the following error:

```
Execution failed for task ':app:transformNativeLibsWithStripDebugSymbolForDebug'.
A problem occurred starting process 'command '/Users/[username]/Library/Android/sdk/ndk-bundle/toolchains/mips64el-linux-android-4.9/prebuilt/darwin-x86_64/bin/mips64el-linux-android-strip''
```

**Comment by yoavrofe** [comment]
Open the android directory in Android Studio, and upgrade gradle. Then copy android/app/build.gradle from the example project, and I think it should work.

**Comment by yoavrofe** [comment]
See also here: https://github.com/AgeOfMobile/flutter_mapbox/issues/2

**Comment by tobrun** [comment]
Correct, following up on this in #55 , for now the steps referenced by @yoavrofe will fix the issue
