### ISSUE TITLE
Development State

### ISSUE THREAD

**Issue by DanielEberl** [mapbox/flutter-mapbox-gl#56]
Hi,

I just found out about MapBox as an alternative to the 'established' maps and really want to integrate this into my company's flutter portation of our existing apps.

I noticed this repo is kind of inactive, so I wonder what the level of progress is right now. If you need some help or manpower,
I would be very happy to help in any kind of matter.

Flutter is really powerful and it's use will be growing exponentially. I believe your company would benefit of providing the first official package for seamless integration of a map in flutter!

Best Regards,
Daniel

**Comment by tobrun** [comment]
Hi @DanielEberl,

As mentioned in the README.md, this isn't an official product (yet). 

>  If you need some help or manpower, I would be very happy to help in any kind of matter.

We are missing iOS integration atm. With this in place we can start making a case to make this an official product. Happy to provide additional information. Closing as this issue as answered but feel free to follow up!
