### ISSUE TITLE
ios support

### ISSUE THREAD

**Issue by ansarikhurshid786** [mapbox/flutter-mapbox-gl#57]
is It also supported ios or not? 

I read the below but not sure current status: 
This Flutter plugin for mapbox-gl-native enables embedded interactive and customizable vector maps inside of a Flutter widget. This project plugin is in early development stage. **Only Android is supported for now.**

**Comment by tobrun** [comment]
We don't have iOS support yet, this is ticketed in #12, we are looking for contributors to make this happen!
