### ISSUE TITLE
Markers and Animation in MapBox SDK

### ISSUE THREAD

**Issue by AnasAVL** [mapbox/flutter-mapbox-gl#60]
Hi, 

I am creating an application in Flutter using dart languages, the new framework created by Google and I am using your MapsBox SDK.

So I got a problem in adding Markers and Animation, I will show you the code below: 
1) MapboxOverlayController 
2) MapboxOverlay 
in pubspec.yaml I am implementing this "mapbox_gl: ^0.0.1" 

overlay_controller.flyTo( 
new CameraPosition( 
target: new LatLng( 
lat:50.0, 
lng:20.0, 
), 
zoom: 12.0), 
5000, 
); 

The above code contains the map but the good thing in it is that the animations like in the MapboxOverlayController is very good to fly to any point using latitude and longitude but the problem is that, this Controller does not have any Options to add Marker in it. 

and please see below as well : 

1) FlutterMap 
2) MapController 
in pubspec.yaml I am implementing this " flutter_map: ^0.0.10 " 

controller.move( 
new LatLng(50.0, 20.0), 
5.0); 

fMap.layers.add( 
new MarkerLayerOptions( 
markers: markerList, 
), 
); 
In the above code, I can add the Marker just on tap on the Map but hte problem is that I can't add the controller to add annimation to move from one point to another point, it just move directly to that point without any animation. 

So please help me how to overcome this kind of problem, as I require both Animation and Markers both. 

- version: Android Version is 16

**Comment by tobrun** [comment]
This project will be moved to https://github.com/tobrun/flutter-mapbox-gl
Marker API through the annotation plugin is one of the most important features to support.
This feature request was added to tobrun/flutter-mapbox-gl#4 (comment)
