### ISSUE TITLE
ios status

### ISSUE THREAD

**Issue by ansarikhurshid786** [mapbox/flutter-mapbox-gl#61]
Hi,
I want use flutter for one project but i am waiting for ios support. 

what is ios support status?

**Comment by KieranSteyn** [comment]
+1 bump

**Comment by zugaldia** [comment]
Hey all, this is currently an experimental project so no active work has been planned (though we love contributions!). I’d love to hear more about what you’re trying to build if you’d like to drop me a line over email (it's listed on my profile) -- hearing directly from developers informs our roadmap. Thanks for your interest!

**Comment by HerrNiklasRaab** [comment]
Webview is now supported, so ios support should not be a problem anymore!

**Comment by HerrNiklasRaab** [comment]
https://github.com/flutter/flutter/issues/19030 we need this!

**Comment by zugaldia** [comment]
[Flutter 1.0](https://developers.googleblog.com/2018/12/flutter-10-googles-portable-ui-toolkit.html) launched yesterday with support for `UiKitView`, which might make iOS integration easier:

> So we've introduced platform view widgets (AndroidView and UiKitView) that let you embed this kind of content on each platform. We've been previewing Android support for a couple of months, but now we're expanding support to iOS, and starting to add plug-ins like Google Maps and WebView that take advantage of this.

**Comment by Fontinalis** [comment]
I got the Mapbox working on my own plugin, so started working on this to implement and going to create a pull request soon!

**Comment by ansarikhurshid786** [comment]
Please let me know once you done and pushed

**Comment by ansarikhurshid786** [comment]
@Fontinalis have you done ?

**Comment by shakes80** [comment]
building a FAA regulations and Weather app focused on drones, love to hear about iOS support.

**Comment by Fontinalis** [comment]
Excuse me for being silent for that long time, but on the other hand, I started [my own implementation](https://github.com/Fontinalis/flunama), which is still under development. I'm sure that this package will be nice and pretty too, I just felt that it's easier for me to start it from scratch. If someone has questions, feel free to reach out!
