### ISSUE TITLE
Is this project abandoned ? 

### ISSUE THREAD

**Issue by adsellor** [mapbox/flutter-mapbox-gl#62]
One of the main functionalities of the app I'm developing is related to maps (directions sdk to be precise). I would very much like to use mapbox as the map provider. The only plugin coming close to this requirement is this one, but it seems it is not maintained anymore and the example is crashing when I try to run it with the latest flutter sdk. @tobrun  Is there any hope that the work on this plugin will be resumed.

**Comment by zugaldia** [comment]
Hey @adesellor, this is currently an experimental project so no active work has been planned. I’d love to hear more about what you’re trying to build if you’d like to drop me a line over email (it's listed on my profile) -- hearing directly from developers informs our roadmap. Thanks for your interest!

**Comment by adsellor** [comment]
Thanks a lot for the response @zugaldia. I'll email you some details, hope it'll help.
