### ISSUE TITLE
Add rotate gesture

### ISSUE THREAD

**Issue by tobrun** [mapbox/flutter-mapbox-gl#7]
A rotate gesture changes the bearing of the camera position of the map.

**Comment by tobrun** [comment]
Flutter doesn't expose a RotateGestureDetector, see full list [here](https://docs.flutter.io/flutter/widgets/GestureDetector/GestureDetector.html).

**Comment by renancaraujo** [comment]
Just added rotation support to ScaleGestureDetector. Pull request: https://github.com/flutter/flutter/pull/17345

**Comment by tobrun** [comment]
with moving to a platform view this issue is no longer applicable, we can leverage touch handling from the native sdks instead.
