### ISSUE TITLE
Locations and Markers

### ISSUE THREAD

**Issue by polly3223** [mapbox/flutter-mapbox-gl#70]
Hi,
I love mapbox and I love flutter, but for now this binder is still insufficient for our needs. 
Are you planning to add support for locationComponent and markers?

**Comment by tobrun** [comment]
location support was added in https://github.com/mapbox/flutter-mapbox-gl/pull/71, we will work more on adding suport for markers through the annotations plugin from https://github.com/mapbox/mapbox-plugins-android/tree/master/plugin-annotation

**Comment by tobrun** [comment]
This project will be moved to https://github.com/tobrun/flutter-mapbox-gl
Marker API through the annotation plugin is one of the most important features to support.
This feature request was added to tobrun/flutter-mapbox-gl#4 (comment)

LocationComponent support was already added with migrating to a platform based integration.
