### ISSUE TITLE
 Comparison between the native mapbox and mapbox flutter

### ISSUE THREAD

**Issue by wuilmerj24** [mapbox/flutter-mapbox-gl#73]
Hi. I'm about to decide whether to develop an app using flutter or native, but there are some doubts about mapbox. What mapis apis will be implemented in this plugin? would it be the same as the APIs implemented in react-native? I want to make an app but I would also like to have 90% of the apis provided by mapbox java, kotlin or swift.

**Comment by tobrun** [comment]
@wuilmerj24 
>  I would also like to have 90% of the apis provided by mapbox java, kotlin or swift.

I would like that as well, to achieve this we will need the help of the community! We have moved the project to https://github.com/tobrun/flutter-mapbox-gl/issues/ make this more a community effort, I hope you have time helping us out with this. 

If you need a stable, ready to go product now, I would suggest using the native sdks instead.
